### PR TITLE
docs: add tutorial for ovs-offline

### LINKED ISSUE #40: Add a Tutorial on how to perform offline debugging with ovs-offline
It should include the process of obtaining the needed information from

- k8s/oc
- osp w/ sos report latest changes
- generic system, w/o latest changes in sos (i.e: based on ovs-save)

And performing:
- basic ovs/ovn introspection
- appctl ofproto/trace
- ovn-detrace

### PR DESCRIPTION
**Pull request by SalDaniele**
fixes #40
Signed-off-by: Salvatore Daniele <sdaniele@redhat.com>

### CODE REVIEW

**Comment by amorenoz** [comment]
We forgot to update the docs on the recently closed #58, would you mind modifying the relevant doc here?

**Comment by amorenoz** [comment]
otherwise lgtm

**Comment by SalDaniele** [comment]
Updated the ovs-offline page of the readthedocs and covered #58 in the tutorial. Anywhere else I should add it?

**Pull request merged**
